events {}

http {
    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name wepopiks.com panelVpn.wepopiks.com;

        # Let’s Encrypt challenge
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            allow all;
        }

        # Всё остальное редиректим на HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Frontend: wepopiks.com
    server {
        listen 443 ssl;
        server_name wepopiks.com;

        ssl_certificate /etc/letsencrypt/live/wepopiks.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wepopiks.com/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://frontend:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # 3x-ui panel: panelVpn.wepopiks.com/panel
    server {
        listen 443 ssl;
        server_name panelVpn.wepopiks.com;

        ssl_certificate /etc/letsencrypt/live/panelVpn.wepopiks.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/panelVpn.wepopiks.com/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;

        location /panel/ {
            proxy_pass http://127.0.0.1:45000/; # так как xui работает в host network
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}